### ISSUE TITLE
Keep Calculators out of authentication

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#171]
Calculators (SIP, EMI, etc) should not require authentication
User/Visitor not signed in to the page should be able to use calculators

**Comment by Edu58** [comment]
I removed authentication from the calculators however. We might have to show the header globally so an unauthenticated user will have access to the calculators links.

**Comment by Edu58** [comment]
I also added the navbar to signin and signup pages so that unauthenticated users can have access to the calculators links. Also straightened a bit. removed unnecessary spacing to the right.
![new-lekka](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/79555732/d386a843-91b8-48c3-bf92-e53ad7d0172d)
